<?php

/**
 * Implements hook_menu_links_discovered_alter().
 */
/* -- might be useful in the future?
function menucustomizer_menu_links_discovered_alter(&$links) {
}
*/

function menucustomizer_preprocess_page(&$variables)
{
    $menu_name = 'main';
    $parameters = new \Drupal\Core\Menu\MenuTreeParameters();
    $parameters->onlyEnabledLinks();
    $tree = \Drupal::menuTree()->load($menu_name, $parameters);

    $newTree = modify_child_links($tree);
    if ($newTree ?? false) {
        $newMenu = \Drupal::menuTree()->build($newTree);
        $variables['page']['sidebar_first']['glenn_theme_mainmenu_2'] = $newMenu;
    }
}

function modify_child_links(&$tree)
{

    $activeTrailService = \Drupal::service('menu.active_trail');

    $activeLink = $activeTrailService->getActiveLink() ?? null;
    if ($activeLink != null)
        $menuLinkDefinition = $activeLink->getPluginDefinition();

    if (!empty($menuLinkDefinition['parent'])) {
        $parentLinkId = $menuLinkDefinition['parent'];
        $parentLink = $tree[$parentLinkId] ?? null;
        return $parentLink->subtree ?? null;
    }
}
